language: node_js
node_js:
- '8'
script: npm run --silent happo-ci
env:
  global:
    secure: mCaYE0kn95lFzaQQOjrvYHIrFEd2bEzteL29d8Khk/QWcuWcLfaSfx2tVe6g+mRLcp1KoyR7QexQhPDqoYHXfMUAGGsxK8NIpE752SSxw9CLFxyCbATZktrlIEZBBEdj2fCIPBvK692R/GTF4t5KqppIRqZLEoZG3z5i84wlZ9xomVsT4ZlPQle99ssRqEQAIglz5rFSXP9au4zCTLi6JtO9mMzEKwYxWaRdgU8UV4756Tap1ingPyNF8hVYVEpe3Z6ld/lxBSqxqUexuVoQKD1E/qZDmY4TzR73gAOE1fvXf1NjqDjfjmReVhtnNgyKTFYXZwfNCETjNtPPsjWWiB6n7QgKhjEBJbSnoJ6LgBdPuSLIGoBuJGo8lH0SQAAeuhAi1IixX+N5XJEGE3t1GNOC82TjCmI8Vn3jnPgmMOIOP3UBcD1vXWBMceTru9FzHhnFXixbNELgqEYBsjd2GbgrFtbF3gWT5oM5tL5UBBIv2KNFNeg6LJidJJk0Wlbjxj8NbSr+ZtLpwFxmEe1gljYPSNxdhMjG9FuoRC43UwINScaStlTWaLhUioffBKCx/7Z9AMrRya9IPQURfUxTnERg97cfIr4w+aHIL73uw/EJxaiMPYBJafxwInLE/XeN8sPNpLX/xvrV4+IgrLzIb3J3hPbO94yKp8jQkfddHLA=
